export const FLICKR_IMAGE = {
  FLICKR_IMAGE_START: 'FLICKR_IMAGE_START',
  FLICKR_IMAGE_SUCCESS: 'FLICKR_IMAGE_SUCCESS',
  FLICKR_IMAGE_FAILURE: 'FLICKR_IMAGE_FAILURE',
};

export const FLICKR_IMAGE_PAGINATION = {
  FLICKR_IMAGE_PAGINATION_START: 'FLICKR_IMAGE_PAGINATION_START',
  FLICKR_IMAGE__PAGINATION_SUCCESS: 'FLICKR_IMAGE__PAGINATION_SUCCESS',
  FLICKR_IMAGE_PAGINATION_FAILURE: 'FLICKR_IMAGE_PAGINATION_FAILURE',
};
